### PR TITLE
Made width of input/output equal to the full width

### PR DESCRIPTION
**Pull request by jlam55555**

### CODE REVIEW

**Comment by jlam55555** [comment]
MUAHAHAHAHA

**Comment by jlam55555** [comment]
MAAHAHAHA

**Comment by jlam55555** [comment]
HAHAHAHAHAHHA

**Comment by jlam55555** [comment]
sdasad

**Comment by jlam55555** [comment]
asdasdasdasdasd

**Comment by jlam55555** [comment]
asdasd

**Comment by rdk750** [comment]
thank you goose egg

**Pull request merged**
